version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "hantsy"
    assignees:
      - "hantsy"
    labels:
      - "dependencies"
      - "maven"
