name: build-api
on:
  push:
    paths:
      - "api/**"
    branches:
      - master
      - release/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      - name: Set up Database
        run: |
          docker-compose up -d postgres
          docker ps -a

      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Resolve Maven dependencies
        run: mvn -B -q clean dependency:go-offline --file api/pom.xml

      - name: Build with Maven
        run: |
          mvn -B -q package --file api/pom.xml -DskipTests
          mvn -B -q test --file api/pom.xml
        
      - name: Build Docker Image
        run: mvn spring-boot:build-image --file api/pom.xml -DskipTests  
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: docker push hantsy/spring-webmvc-auth0-sample-api:latest     

  automerge:
    name: Merge pull request
    runs-on: ubuntu-latest
    needs: [ build-api ]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge
        uses: actions/github-script@v4.0.2
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
